services:
  laksh-front:
    container_name: laksh-front-container
    build: .
    image: laksh-front
    ports:
    - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
