services:
  laksh-front:
    container_name: laksh-front-container
    build: .
    image: laksh-front
    ports:
    - 80:4000
    expose:
      - 4000
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
